// lib/firebase_options.dart
// File generated by FlutterFire CLI. (edited)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run FlutterFire CLI again if you need it.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ----- Web -----
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnPkUBHQG7n2weuJjUkf2CMKUdhyOPYA',
    appId: '1:816265988648:web:f1270d76bb5846e1bc031d',
    messagingSenderId: '816265988648',
    projectId: 'fiber-calculator-app',
    authDomain: 'fiber-calculator-app.firebaseapp.com',
    // IMPORTANT: use *.appspot.com for Flutter SDKs
    storageBucket: 'fiber-calculator-app.appspot.com',
    measurementId: 'G-8YE8E8KZ6B',
  );

  // ----- Android -----
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1Ta3zN0RZfGbDo7go0kxS7B38Bnuc9Uk',
    appId: '1:816265988648:android:fdacbd213fe7db9bbc031d',
    messagingSenderId: '816265988648',
    projectId: 'fiber-calculator-app',
    storageBucket: 'fiber-calculator-app.appspot.com',
  );

  // ----- iOS -----
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfwsr49wa1uGY6GeMcukUjhFzV7x-W5U8',
    appId: '1:816265988648:ios:689381b70644d31fbc031d',
    messagingSenderId: '816265988648',
    projectId: 'fiber-calculator-app',
    storageBucket: 'fiber-calculator-app.appspot.com',
    iosBundleId:
        'com.example.fiberCounterApp', // ปรับให้ตรงกับ Bundle ID จริงถ้าไม่ตรง
  );

  // ----- macOS (ใช้ค่าเดียวกับ iOS) -----
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfwsr49wa1uGY6GeMcukUjhFzV7x-W5U8',
    appId: '1:816265988648:ios:689381b70644d31fbc031d',
    messagingSenderId: '816265988648',
    projectId: 'fiber-calculator-app',
    storageBucket: 'fiber-calculator-app.appspot.com',
    iosBundleId: 'com.example.fiberCounterApp',
  );

  // ----- Windows (ถ้าใช้ Flutter Desktop) -----
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKnPkUBHQG7n2weuJjUkf2CMKUdhyOPYA',
    appId: '1:816265988648:web:9f8d3ffbd8a2e6d4bc031d',
    messagingSenderId: '816265988648',
    projectId: 'fiber-calculator-app',
    authDomain: 'fiber-calculator-app.firebaseapp.com',
    storageBucket: 'fiber-calculator-app.appspot.com',
    measurementId: 'G-K5MFEHNDXE',
  );
}
